### ISSUE TITLE
Automatically escape quotes in the search query

### ISSUE THREAD

**Issue by tmr232** [agrmohit/omnivore-epub#5]
I wanted to only take _some_ articles, chosen by a label, as there are some that I prefer to read on my phone.

So I created a label and changed the search query: `sort:saved-desc label:"Send to Kindle"`.

To escape it properly, I had to do double escaping - once for the JSON file, and once for the GQL request:

```
  "searchQuery": "sort:saved-desc label:\\\"Send to Kindle\\\"",
```

I think it would be nice if the script did the escaping-for-GQL on its own.

**Comment by agrmohit** [comment]
Hi Tamir,

Thanks for pointing out this shortcoming and creating a PR for it (#6).
I feel it might be a common enough requirement to warrant a dedicated config property. So I have created a PR for it (#7).

Please try it and let me know if it solves your requirement.

**Comment by tmr232** [comment]
It doesn't solve the issue for me.

The label filtering now happens _after_ fetching the articles. 
This means that if I set my `maxArticleCount` to 10, and the first 10 articles don't have a matching label - I won't get any articles.
Additionally, it leads to extra API calls to fetch articles before checking their labels.

I think having a config option for labels is nice, but it should work towards the query, not post-filtering.
And since I can always create my "advanced" query string by doing the search on Omnivore, checking the results, and then copying the search query - I personally don't see the need for any support other than the query string itself at the moment.

**Comment by agrmohit** [comment]
Thanks for clearing it up. I keep my Omnivore library small by archiving read articles and don't use saved searches or query strings often. So I didn't think about this.

I will merge your version as its more versatile and add a note about escaping double quotes.
