### ISSUE TITLE
Errors out with too many requests

### ISSUE THREAD

**Issue by linnabraham** [agrmohit/omnivore-epub#9]
I am not exactly sure how many articles are there in my omnivore. The account settings show 289 items. I set the maxArticles to 300 and also set to exclude 1 label which has maybe 30 articles or so attached. First time I saw that it didnt error out but only few articles were there in the ouput. So I ran again and I got this error. 

```
error: Uncaught (in promise) Error: GraphQL Error (Code: 429): {"response":{"error":"Too many requests, please try again later.","status":429,"headers":{}},"request":{"query":"{\n    article (username: \"anonymous\", slug: \"2-2-cross-validation-stat-508-18d50ca7b53\") {\n      ... on ArticleSuccess {\n        article {\n          id, slug, url, content\n        }\n      }\n    }\n  }"}}
    at makeRequest (file:///home/linn/.cache/deno/npm/registry.npmjs.org/graphql-request/6.1.0/build/esm/index.js:282:15)
    at Object.runMicrotasks (ext:core/01_core.js:659:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:176:21)
    at async getArticle (file:///home/linn/work/archived/2023/aug2023/omniexp-jackson/newexp/omnivore-epub/main.ts:125:16)
    at async makeEbook (file:///home/linn/work/archived/2023/aug2023/omniexp-jackson/newexp/omnivore-epub/main.ts:163:22)
    at async file:///home/linn/work/archived/2023/aug2023/omniexp-jackson/newexp/omnivore-epub/main.ts:217:1
```

**Comment by agrmohit** [comment]
Hi, thanks for reporting the issue.

In the latest release (v0.6.0) I have switched to using official omnivore api library. It fetches the article content at the same time as the article listings.

Can you try it and see if the issue still persists.

Omnivore's rate limit seems to be [100 requests per minute](https://github.com/omnivore-app/omnivore/blob/bfc1be6546b6316f2488dee7d8035453625aa93f/packages/api/src/server.ts#L78), so with about 300 articles, you would definitely exceed that with the previous method of an api call per article.

**Comment by linnabraham** [comment]
Thanks for the quick fix you provided. It works now for 100 articles. From what you said I guess this is the limit that omnivore places. Can this limit be bypassed in any way? Is it possible to add a delay of a minute until the total number is fetched?

**Comment by agrmohit** [comment]
I pushed a new pr #10 that adds the delay. Articles are fetched in batches of 60 at a time because Omnivore code was a bit confusing on whether the actual number is 60 or 100.

Hope this solves your issue.

**Comment by linnabraham** [comment]
Thanks. It works perfect.

**Comment by agrmohit** [comment]
Thats nice to hear. Will merge it in the main branch.
